apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-pipeline-deploy-k8s
  namespace: default
spec:
  selector:
    matchLabels:
      app: jenkins-spring-boot-demo
  template:
    metadata:
      labels:
        app: jenkins-spring-boot-demo
    spec:
      containers:
      - image: yigongzi/spring-boot-shopping-cart:<BUILD_ID>
        imagePullPolicy: IfNotPresent
        name: jenkins-spring-boot-demo
        ports:
        - containerPort: 8070


---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: jenkins-spring-boot-demo
  ports:
  - name: webapp
    protocol: TCP
    port: 8070
    targetPort: 8070
    nodePort: 30008
